[build]
  command = "npm run build"
  publish = "web-build" # Zmień na katalog, w którym Expo tworzy build (np. 'dist')

[functions]
  directory = "functions/dist" 
  node_bundler = "esbuild"

[dev]
  targetPort = 8081 
  port = 8888